### ISSUE TITLE
Any plans on a swift version?

### ISSUE THREAD

**Issue by kiwo12345** [StyleShare/SSBouncyButton#2]

**Comment by devxoul** [comment]
Hi @kiwo,
Why do you need its Swift version?

**Comment by kiwo12345** [comment]
Hi @devxoul 
I would like to implement this in one of my projects, but I don't understand Objective-C that good.
I could ofc just make a bridge header, but I still wouldnt understand the code that good

**Comment by devxoul** [comment]
Which do you mean: just 'using' or 're-implementing' in your own way?
If the former, I can provide you a [sample code](https://github.com/StyleShare/SSBouncyButton/blob/master/SSBouncyButtonDemo/SSBouncyButtonDemo/SSAppDelegate.m#L44:L59) in Swift.

**Comment by kiwo12345** [comment]
@devxoul sorry using, if you have the code written in swift that would be great!

**Comment by devxoul** [comment]
@kiwo12345,

This is the [highlighted code](https://github.com/StyleShare/SSBouncyButton/blob/master/SSBouncyButtonDemo/SSBouncyButtonDemo/SSAppDelegate.m#L44:L59) in Swift:

```swift
let followButton = SSBouncyButton(frame: CGRect(x: 0, y: 0, width: 100, height: 40))
followButton.center = CGPoint(x: centerX, y: centerY - 25)
followButton.setTitle("Follow", forState: .Normal)
followButton.setTitle("Following", forState: .Selected)
followButton.addTarget(self, action: "buttonDidPress:", forControlEvents: .TouchUpInside)
self.window.addSubview(followButton)

// tintColor, cornerRadius
let customButton = SSBouncyButton(frame: CGRect(x: 0, y: 0, width: 100, height: 40))
customButton.center = CGPoint(x: centerX, y: centerY + 25);
customButton.tintColor = UIColor.grayColor()
customButton.cornerRadius = 5
customButton.setTitle("Follow", forState: .Normal)
customButton.setTitle("Following", forState: .Selected)
customButton.addTarget(self, action: "buttonDidPress:", forControlEvents: .TouchUpInside)
self.window.addSubview(customButton)
```

I hope this will help you.

**Comment by kiwo12345** [comment]
@devxoul Thank you!

**Comment by devxoul** [comment]
:smile::+1:
